"""Add notification fields

Revision ID: 5642bd73b6d8
Revises: add_is_archived_column
Create Date: 2026-01-27 23:48:50.482711

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5642bd73b6d8"
down_revision = "add_is_archived_column"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    # op.drop_table('topology')
    # op.drop_table('layer')
    op.add_column("driver", sa.Column("last_online_at", sa.DateTime(), nullable=True))
    op.add_column("user", sa.Column("fcm_token", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "fcm_token")
    op.drop_column("driver", "last_online_at")
    op.create_table(
        "layer",
        sa.Column("topology_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("layer_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("schema_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("table_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("feature_column", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("feature_type", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "level",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("child_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["topology_id"], ["topology.id"], name=op.f("layer_topology_id_fkey")
        ),
        sa.PrimaryKeyConstraint("topology_id", "layer_id", name=op.f("layer_pkey")),
        sa.UniqueConstraint(
            "schema_name",
            "table_name",
            "feature_column",
            name=op.f("layer_schema_name_table_name_feature_column_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "topology",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "precision",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "hasz",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("topology_pkey")),
        sa.UniqueConstraint(
            "name",
            name=op.f("topology_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "srid > 0 AND srid <= 998999", name=op.f("spatial_ref_sys_srid_check")
        ),
        sa.PrimaryKeyConstraint("srid", name=op.f("spatial_ref_sys_pkey")),
    )
    # ### end Alembic commands ###
