include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Error Rules
    avoid_empty_else: true
    avoid_print: true # Use Logger instead
    avoid_relative_lib_imports: true
    avoid_types_as_parameter_names: true
    control_flow_in_finally: true
    empty_statements: true
    hash_and_equals: true
    no_duplicate_case_values: true
    throw_in_finally: true
    unrelated_type_equality_checks: true

    # Style Rules
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    annotate_overrides: true
    avoid_init_to_null: true
    avoid_multiple_declarations_per_line: true
    avoid_shadowing_type_parameters: true
    camel_case_types: true
    constant_identifier_names: true
    curly_braces_in_flow_control_structures: true
    directives_ordering: true
    file_names: true
    library_names: true
    library_prefixes: true
    non_constant_identifier_names: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    slash_for_doc_comments: true
    type_init_formals: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_this: true
    use_function_type_syntax_for_parameters: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
  errors:
    invalid_annotation_target: ignore
